### ISSUE TITLE
Add option --coverage

### ISSUE THREAD

**Issue by svycka** [prolic/HumusPHPUnitModule#14]
maybe `--coverage-html`, `--coverage-clover` etc
I don't know what would be better one coverage for all modules or each module would have separete coverage. What do you think?

**Comment by prolic** [comment]
Coverage should be done per module. that means, you should probably put it into your phpunit.xml file.
If you have 2 modules and want to have coverage for both, how would you like to do that from command line?

**Comment by svycka** [comment]
I dont know how :D mabe your module should generate phpunit.xml or something. And how Can I put something in phpunit.xml I dont think that I want coverage evry time i run tests

**Comment by prolic** [comment]
An idea, 2 modules: ModuleA and ModuleB

start with:

humusphpunit --coverage-html=html

then what we create is:

html/ModuleA/index.html <- coverage for ModuleA
html/ModuleB/index.html <- coverage for ModuleB

What do you think?

**Comment by svycka** [comment]
I think this would be easier.

but if I want to test whole application not a module then not so good because coverage generates 'Change Risk Anti-Patterns (CRAP) Index' for example and in your suggested way this would be a problem.

but for module testing I think this would be ok. Just I think that this module is for application testing not for module, for one module you can just use phpunit. Am I wrong?

**Comment by prolic** [comment]
What's the difference between testing a module and testing an application? An application in zf2 is also a module, even if you do everything in a common "Application"-Module, it's still a module.

**Comment by svycka** [comment]
The difference is that app can depend on 3 or more modules and I want to test them working together. Thats more like integration test not unit tests.

**Comment by prolic** [comment]
In this case, you would define a phpunit.xml file and add it to humusphpunit under the name "MyApp" or whatever you like. You will get code coverage for your project under the directory "MyApp", and all other modules can still be tested in isolation, too.

**Comment by svycka** [comment]
yes but as i said CRAP index would be counted for each module not for all. lets say I have module like UserModule and this module itself doesn't do much but other modules uesing it much so to see that user module is used I have to check all others and see if they use it. No? and if I would have one coverage for all my modules and all tests I could see all in one place

**Comment by prolic** [comment]
First of all, you have independent phpunit results for every tested module, if I pass the --coverage option, I need to create a subdirectory named by the module to store it's assets (coverage e.g.).

Second, if you want to have code coverage for a given modules incl. dependent modules, f.e. even incl. zf2 itself, you simple configure your phpunit.xml file accordingly.

See: Including and Excluding Files for Code Coverage
http://phpunit.de/manual/3.7/en/appendixes.configuration.html#appendixes.configuration.blacklist-whitelist

You can simply add dependent modules files to coverage whitelist, if you wish that.

If you test 2 libraries with humusphpunit, f.e. "Zend Framework 2" and "Doctrine Common", there is no common coverage and a common coverage measurement would not be reasonable. You can pass as many phpunit.xml files to humusphpunit as you want.

**Comment by svycka** [comment]
Ok then maybe its time to think why I am using this module. Because all it does is

```
foreach modules {
    phpunit -c path/to/module/tests
}
```

and limits me to use almost all phpunit features(some will be added in next version of this module). Maybe I am missing something? If you creating this module then it should add functionality not limit me what I can do. What do you think?

**Comment by prolic** [comment]
You are right, all this module does is:

```
foreach modules {
    phpunit -c path/to/module/tests
}
```

with the additonal parameters, that are implemented or planned, to be implemented.

What you know expect from me (please correct me, if I am wrong):

```
phpunit -c path/to/module1
phpunit -c path/to/module2
```

and then check path/to/coverage and see both coverage results merged in one coverage report. How should that work?

It is designed to run multiple phpunit calls in sequence, every phpunit run has it's own assets generated.

**Comment by svycka** [comment]
Hmm, yep it's hard to accomplish..
I don't know maybe generate phpunit.xml with testsuites from all configured modules, so just one problem how to bootstrap.. maybe add path to bootstrap file to configuration :D or maybe not. I guess it would be good enough your suggested way  for now :)

**Comment by gsomoza** [comment]
Just out of curiosity: what's the problem with configuring those options [through `phpunit.xml`](https://phpunit.de/manual/current/en/appendixes.configuration.html#appendixes.configuration.logging)? In my case I'm doing that and pointing the coverage files wherever I want, where my CI system picks them up for further analysis. E.g. I'm sending all coverage results to `../../data/tests-results/coverage/moduleName.xml`.

So I think it makes sense not to provide the ability to supply command-line parameters specific for each PhpUnit call, since this is a command meant to run tests across multiple modules. Not having those parameters keeps this codebase slim and simple to use, and forces users to take advantage of PHP Unit features they otherwise wouldn't.

IF you ever consider supporting parameters then I'd suggest a syntax as follows: `--moduleName-phpunit-parameter=value`, and then simply remove the prefix and send those parameters to the corresponding module exactly as they're supplied - i.e. not even whitelist them: just allow `--moduleName-anything` to generate `--anything` on the phpunit call.

**Comment by prolic** [comment]
@gabrielsomoza Good catch! Unfortunately I don't have much time currently to invest into this project as I am planning and releasing other Open Source Projects, soon.

**Comment by prolic** [comment]
As @gabrielsomoza suggested, for --coverage options, it's better to configure it via phpunit.xml file.
