### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ThaDafinser** [prolic/HumusPHPUnitModule#2]
Just tried this module with WIN7.

To get it run i've changed following code in the Runner:

``` php
public function run()
    {
        echo "Humus PHPUnit Module for Zend Framework 2\n";
        echo "Author: Sascha-Oliver Prolic\n\n";
        foreach ($this->getTests() as $module => $paths) {
            echo 'Testing Module: ' . $module . "\n";
            foreach ($paths as $path) {
                passthru('vendor\bin\phpunit -c ' . realpath($path));
            }

        }
        echo "\nAll done.";
    }
``

The problem is the path with "/".
```

**Comment by prolic** [comment]
I don't have windows for development ;-) sorry.

Could you try the following and report the result to me?

passthru('vendor' . DIRECTORY_SEPARATOR . 'bin' . DIRECTORY_SEPARATOR . 'phpunit -c ' . realpath($path));

or

passthru('php vendor' . DIRECTORY_SEPARATOR . 'bin' . DIRECTORY_SEPARATOR . 'phpunit -c ' .

**Comment by prolic** [comment]
solved by https://github.com/prolic/HumusPHPUnitModule/commit/7805118ffa407c199207c1ae02228bfd3638e2cf

thanks
